name    'mpf-kvlog'
version '0.0.2'
source 'UNKNOWN'
author 'mpf'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'A Puppet report processor for sending metrics to syslog.'
project_page 'https://github.com/mattimustang/puppet-kvlog'
